### ISSUE TITLE
“收回訊息功能”問題

### ISSUE THREAD

**Issue by zxcjeff000** [m4fn3/k2ge3-trollstore#1]
您好，如果在關閉line及背景運作 “收回訊息功能”將失效，必須運行Line或使用Line 才生效。

系統版本Ios17.0 Trollstore

**Comment by m4fn3** [comment]
This is a known issue. Please use some tweak like Senri to save notifs
instead.

2024年9月7日(土) 18:19 zxcjeff000 ***@***.***>:
