### ISSUE TITLE
プロフィールを表示できない

### ISSUE THREAD

**Issue by tqmane** [m4fn3/k2ge3-trollstore#2]
最新バージョン（14.6.1）において、プロフィールを表示するとアプリがクラッシュします。

iPhone8 Trollstore iOS16.7.9

**Comment by m4fn3** [comment]
https://x.com/m4fn3/status/1819665653701251152?s=46&t=_V8Xt_UQCUvTHe6yCnaWgQ
こちらをご確認ください

2024年10月14日(月) 14:58 たまねぎ研究事務所 ***@***.***>:
